server.port=8765

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://naming-server:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${EUREKA_INSTANCE_IP_ADDRESS}
spring.cloud.inetutils.preferred-networks=172\.31\..*

# JWT
jwt.secret=${JWT_SECRET}