server.port=8765
eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

jwt.secret=this-is-a-very-long-secret-key-for-user-service-jwt-2026

#spring.cloud.gateway.discovery.locator.enabled=true
