server.port=8081

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/order_service_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://naming-server:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${EUREKA_INSTANCE_IP_ADDRESS}
spring.cloud.inetutils.preferred-networks=172\.31\..*

# OrderCreatedEvent queues
payment.order.created.queue.name=payment.order.created.queue
notification.order.created.queue.name=notification.order.created.queue

# OrderCreatedEvent routing keys
payment.order.created.routing.key=payment.order.created.key
notification.order.created.routing.key=notification.order.created.key

# Order exchange
order.exchange.name=order.exchange

# PaymentCompletedEvent consumer queue
order.payment.completed.queue.name=order.payment.completed.queue