server.port=8082

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/payment_service_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://naming-server:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${EUREKA_INSTANCE_IP_ADDRESS}
spring.cloud.inetutils.preferred-networks=172\.31\..*

# PaymentCompletedEvent queues
order.payment.completed.queue.name=order.payment.completed.queue
notification.payment.completed.queue.name=notification.payment.completed.queue

# PaymentCompletedEvent routing keys
order.payment.completed.routing.key=order.payment.completed.key
notification.payment.completed.routing.key=notification.payment.completed.key

# Payment exchange
payment.exchange.name=payment.exchange

# OrderCreatedEvent consumer queue
payment.order.created.queue.name=payment.order.created.queue